export const LIQUIBASE_OPTIONAL_PARAMETERS = [
  "--propertyProviderClass",
  "--promptForNonLocalDatabase",
  "--logLevel",
  "--logFile",
  "--liquibaseProLicenseKey",
  "--includeSystemClasspath",
  "--help",
  "--dataOutputDirectory",
  "--defaultsFile",
  "--defaultSchemaName",
  "--databaseClass",
  "--currentDateTimeFunction",
  "--contexts",
  "--classpath",
];
